# Generated by Django 5.2.8 on 2025-11-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="counter_views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счётчик просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="slug"
            ),
        ),
    ]
