# Generated by Django 5.2.8 on 2025-11-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_alter_post_counter_views_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Признак публикации"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=255, verbose_name="slug"),
        ),
    ]
