# Generated by Django 5.2.8 on 2025-11-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Электронная почта"),
                ),
                ("about_me", models.TextField(verbose_name="Информация о себе")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
