# Generated by Django 5.2.8 on 2025-11-23 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_num",
                    models.PositiveSmallIntegerField(verbose_name="номер версии"),
                ),
                (
                    "version_name",
                    models.CharField(max_length=64, verbose_name="название версии"),
                ),
                (
                    "is_actual",
                    models.BooleanField(default=False, verbose_name="Текущая версия"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
    ]
