# Generated by Django 5.2.8 on 2025-11-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(max_length=64, verbose_name="Название версии"),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_num",
            field=models.PositiveSmallIntegerField(verbose_name="Номер версии"),
        ),
    ]
