# Generated by Django 5.2.8 on 2025-11-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_cancel_publish", "Может отменять публикацию"),
                    ("can_change_category", "Может менять категорию"),
                    ("can_change_description", "Может менять описание"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
